### ISSUE TITLE
是否不支持蓝叠模拟器国际版

### ISSUE THREAD

**Issue by 761385450** [MistEO/MeoAssistance-Arknights#15]
用的国际版的蓝叠5模拟器 辅助不能检测到窗口

**Comment by MistEO** [comment]
之前版本的架构有问题，确实是不支持的。最近刚重构了一下，会尝试去支持所有主流模拟器，敬请期待\(^o^)/~

**Comment by MistEO** [comment]
最新测试版已修复，https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/release.beta.08.03
