### ISSUE TITLE
蓝叠模拟器Hyper-V版无法正常连接

### ISSUE THREAD

**Issue by cglcv** [MistEO/MeoAssistance-Arknights#19]
蓝叠模拟器Hyper-V版ADB的端口似乎是随机分配的，并非预设的5555端口，希望能添加一个输入特定端口或IP地址的位置

**Comment by MistEO** [comment]
Hyper-V版是啥版本？搜了下没看到_(:з」∠)_

端口改下`resource/config.json`就好，不过对应的模拟器窗口句柄名也要改下

**Comment by cglcv** [comment]
但还是希望加一个自定义端口的模式……模拟器每次启动都会随机更改连接端口

**Comment by MistEO** [comment]
下次一定！

另外我看了下，蓝叠国际版的5版本，64bit的，也是支持Hyper-V的，可以试试_(:з」∠)_那个端口不会变
https://www.bluestacks.com/download.html

![image](https://user-images.githubusercontent.com/18511905/136703567-37200659-6281-4fd3-9929-3664fd7c6660.png)

**Comment by MistEO** [comment]
> > 下次一定！
> > 另外我看了下，蓝叠国际版的 5 版本 ，64bit 的，也是支持 Hyper-V 的，可以试试_(:з」∠)_那个端口不会变 https://www.bluestacks.com/download.html
> > ![image](https://user-images.githubusercontent.com/18511905/136703567-37200659-6281-4fd3-9929-3664fd7c6660.png)
> 
> 😭 我试过之后每次都在变耶...

奇怪我用的就是这个一直没有变过呀。。不过最近确实准备重构adb连接这块的逻辑，咋知道端口变了呢，adb devices直接就能看到？不用adb connect么？

**Comment by cglcv** [comment]
hyper-V版的蓝叠模拟器设置里面显示的端口每一次都不一样，可能是hyper-V版特有的操作吧……-------- 原始邮件 --------发件人： MistEO ***@***.***>日期： 2021年10月31日周日 23:00收件人： MistEO/MeoAssistance-Arknights ***@***.***>抄送： cglcv ***@***.***>, Author ***@***.***>主    题： Re: [MistEO/MeoAssistance-Arknights] 蓝叠模拟器Hyper-V版无法正常连接 (#19)





下次一定！

另外我看了下，蓝叠国际版的 5 版本 ，64bit 的，也是支持 Hyper-V 的，可以试试_(:з」∠)_那个端口不会变 https://www.bluestacks.com/download.html





😭 我试过之后每次都在变耶...



奇怪我用的就是这个一直没有变过呀。。不过最近确实准备重构adb连接这块的逻辑，咋知道端口变了呢，adb devices直接就能看到？不用adb connect么？

**Comment by miyouzi** [comment]
> > > 下次一定！
> > > 另外我看了下，蓝叠国际版的 5 版本 ，64bit 的，也是支持 Hyper-V 的，可以试试_(:з」∠)_那个端口不会变 https://www.bluestacks.com/download.html
> > > ![image](https://user-images.githubusercontent.com/18511905/136703567-37200659-6281-4fd3-9929-3664fd7c6660.png)
> > 
> > 
> > 😭 我试过之后每次都在变耶...
> 
> 奇怪我用的就是这个一直没有变过呀。。不过最近确实准备重构adb连接这块的逻辑，咋知道端口变了呢，adb devices直接就能看到？不用adb connect么？

当系统启用 HyperV 的时候，才会出现 adb 端口随机问题，而且神奇的是一开始 `adb devices` 是查不出来的，`netstat -ano` 也查不出监听端口，得手动 `adb connect` 后，`adb devices` 才能查出来，端口才开始监听

**Comment by Meow-2** [comment]
因为要用WSL2，所以我的Windows一直开启着Hyper-V功能，开启了Hyper-V之后，每次运行蓝叠5（Hyper-V国际版），adb调试桥开放的端口都不一样

**Comment by Meow-2** [comment]
> > > 下次一定！
> > > 另外我看了下，蓝叠国际版的 5 版本 ，64bit 的，也是支持 Hyper-V 的，可以试试_(:з」∠)_那个端口不会变 https://www.bluestacks.com/download.html
> > > ![image](https://user-images.githubusercontent.com/18511905/136703567-37200659-6281-4fd3-9929-3664fd7c6660.png)
> > 
> > 
> > 😭 我试过之后每次都在变耶...
> 
> 奇怪我用的就是这个一直没有变过呀。。不过最近确实准备重构adb连接这块的逻辑，咋知道端口变了呢，adb devices直接就能看到？不用adb connect么？

只要电脑开启了 Hyper-V ，蓝叠5 Hyper-V版每次启动就会变端口，改变的端口无法通过 adb 指令知道，端口的值可以在`BlueStacks_nxt/bluestacks.conf` 中的`bst.instance.Nougat64.status.adb_port = xxxx` 那里查看

**Comment by Meow-2** [comment]
> 但还是希望加一个自定义端口的模式……模拟器每次启动都会随机更改连接端口

我自己写了个简陋的脚本，填上你 蓝叠5 HyperV 和 MeoAssistance 的目录地址可以凑合先着用。启动蓝叠后，**管理员**运行该脚本会读取蓝叠的 adb 端口并写进 MeowAssistance 的配置文件 ，之后自动打开 MeowAssistance

```
#include <fstream>
#include <string>
#include <cstring>
#include <vector>
#include <windows.h>

std::string &getIpPort(const std::string &inPath, std::string &ipPort)
{
    std::ifstream inFile;
    std::string line;
    inFile.open(inPath, std::ifstream::in);
    while (std::getline(inFile, line))
    {
        char *strs = new char[line.length() + 1];
        std::strcpy(strs, line.c_str());
        char *partOne = std::strtok(strs, "=\"");
        char *parTwo = std::strtok(NULL, "=\"");
        if (std::strcmp(partOne, "bst.instance.Nougat64.status.adb_port") == 0)
        {
            ipPort = parTwo;
            return ipPort;
        }
    }
    return ipPort;
}

void changeIpPort(const std::string &json_path, const std::string &ipPort)
{
    std::ifstream inFile;
    std::string line;
    std::vector<std::string> lines;
    inFile.open(json_path, std::ifstream::in);
    while (std::getline(inFile, line))
    {
        lines.push_back(line);
    }
    //更具实际config文件的情况修改，lines[]中的数字应为config对应行中的数字减一
    lines[51] = "                \"connect\": \"[Adb] connect 127.0.0.1:" + ipPort + "\",";
    lines[52] = "                \"click\": \"[Adb] -s 127.0.0.1:" + ipPort + " shell input tap [x] [y]\",";
    lines[53] = "                \"swipe\": \"[Adb] -s 127.0.0.1:" + ipPort + " shell input swipe [x1] [y1] [x2] [y2] [duration]\",";
    lines[54] = "                \"display\": \"[Adb] -s 127.0.0.1:" + ipPort + " shell dumpsys window displays | grep init= | awk \' { print $3 } \'\",";
    lines[56] = "                \"screencap\": \"[Adb] -s 127.0.0.1:" + ipPort + " exec-out screencap -p\"";
    inFile.close();
    std::ofstream outFile;
    outFile.open(json_path, std::ofstream::out);
    for (auto &i : lines)
    {
        outFile << i << '\n';
    }
}

int main()
{
    //使用流程，将本文件编译成 exe ,在启动蓝叠Hyper-v版后，管理员运行本文件的exe即可自动更改adb端口号，然后启动MeoAssistance
    //蓝叠5文件夹目录
    std::string buleStacks("C:\\Users\\Public\\MyInstall\\BlueStacks_nxt");
    //MeoAssistance文件夹目录
    std::string meoAssistance("C:\\Users\\zk\\Downloads\\MeoAssistance");

    std::string inPath(buleStacks + "\\bluestacks.conf");
    std::string outPath(meoAssistance + "\\resource\\config.json");
    std::string ipPort = "";
    ipPort = getIpPort(inPath, ipPort);
    changeIpPort(outPath, ipPort);
    //开启 MeoAsstGui.exe
    WinExec("C:\\Users\\zk\\Downloads\\MeoAssistance\\MeoAsstGui.exe", SW_SHOW);
}
```

**Comment by MistEO** [comment]
> > 但还是希望加一个自定义端口的模式……模拟器每次启动都会随机更改连接端口
> 
> 我自己写了个简陋的脚本，填上你 蓝叠5 HyperV 和 MeoAssistance 的目录地址可以凑合先着用。启动蓝叠后，**管理员**运行该脚本会读取蓝叠的 adb 端口并写进 MeowAssistance 的配置文件 ，之后自动打开 MeowAssistance
> 
> ```
> #include <fstream>
> #include <string>
> #include <cstring>
> #include <vector>
> #include <windows.h>
> 
> std::string &getIpPort(const std::string &inPath, std::string &ipPort)
> {
>     std::ifstream inFile;
>     std::string line;
>     inFile.open(inPath, std::ifstream::in);
>     while (std::getline(inFile, line))
>     {
>         char *strs = new char[line.length() + 1];
>         std::strcpy(strs, line.c_str());
>         char *partOne = std::strtok(strs, "=\"");
>         char *parTwo = std::strtok(NULL, "=\"");
>         if (std::strcmp(partOne, "bst.instance.Nougat64.status.adb_port") == 0)
>         {
>             ipPort = parTwo;
>             return ipPort;
>         }
>     }
>     return ipPort;
> }
> 
> void changeIpPort(const std::string &json_path, const std::string &ipPort)
> {
>     std::ifstream inFile;
>     std::string line;
>     std::vector<std::string> lines;
>     inFile.open(json_path, std::ifstream::in);
>     while (std::getline(inFile, line))
>     {
>         lines.push_back(line);
>     }
>     //更具实际config文件的情况修改，lines[]中的数字应为config对应行中的数字减一
>     lines[51] = "                \"connect\": \"[Adb] connect 127.0.0.1:" + ipPort + "\",";
>     lines[52] = "                \"click\": \"[Adb] -s 127.0.0.1:" + ipPort + " shell input tap [x] [y]\",";
>     lines[53] = "                \"swipe\": \"[Adb] -s 127.0.0.1:" + ipPort + " shell input swipe [x1] [y1] [x2] [y2] [duration]\",";
>     lines[54] = "                \"display\": \"[Adb] -s 127.0.0.1:" + ipPort + " shell dumpsys window displays | grep init= | awk \' { print $3 } \'\",";
>     lines[56] = "                \"screencap\": \"[Adb] -s 127.0.0.1:" + ipPort + " exec-out screencap -p\"";
>     inFile.close();
>     std::ofstream outFile;
>     outFile.open(json_path, std::ofstream::out);
>     for (auto &i : lines)
>     {
>         outFile << i << '\n';
>     }
> }
> 
> int main()
> {
>     //使用流程，将本文件编译成 exe ,在启动蓝叠Hyper-v版后，管理员运行本文件的exe即可自动更改adb端口号，然后启动MeoAssistance
>     //蓝叠5文件夹目录
>     std::string buleStacks("C:\\Users\\Public\\MyInstall\\BlueStacks_nxt");
>     //MeoAssistance文件夹目录
>     std::string meoAssistance("C:\\Users\\zk\\Downloads\\MeoAssistance");
> 
>     std::string inPath(buleStacks + "\\bluestacks.conf");
>     std::string outPath(meoAssistance + "\\resource\\config.json");
>     std::string ipPort = "";
>     ipPort = getIpPort(inPath, ipPort);
>     changeIpPort(outPath, ipPort);
>     //开启 MeoAsstGui.exe
>     WinExec("C:\\Users\\zk\\Downloads\\MeoAssistance\\MeoAsstGui.exe", SW_SHOW);
> }
> ```

哇，好耶！找时间我整理进项目里，感谢大佬！

**Comment by MistEO** [comment]
已修复[34c5089](https://github.com/MistEO/MeoAssistance-Arknights/commit/34c50898d500e91c5a19829d70214de4bccb9905)，请尝试[v1.3-beta.3](https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v1.3-beta.3)版本

@miyouzi @cglcv @melosbot @Meow-2

**Comment by miyouzi** [comment]
@MistEO HyperV版还是不能自动连上
![image](https://user-images.githubusercontent.com/24269465/140843751-18b5e137-a698-42fa-8d15-cf9b1fd16d14.png)

似乎没有使用读取蓝叠配置文件的方法，而是使用蓝叠目录下的 adb，但是 `adb devices` 在 HyperV 下无法直接读出模拟器
![image](https://user-images.githubusercontent.com/24269465/140844159-04e6183c-4bcb-4ab0-90fc-a8e78a54a10e.png)


**Log：**
```
[2021-11-09 09:17:03.406][TRC][Px696c][Tx56b0] asst::Assistance::catch_default  | enter 
[2021-11-09 09:17:03.406][TRC][Px696c][Tx56b0] asst::Assistance::catch_emulator  | enter 
[2021-11-09 09:17:03.407][TRC][Px696c][Tx56b0] asst::Assistance::stop  | enter 
[2021-11-09 09:17:03.407][TRC][Px696c][Tx56b0] Stop | block 
[2021-11-09 09:17:03.407][TRC][Px696c][Tx56b0] asst::Assistance::stop  | leave, 0 ms 
[2021-11-09 09:17:03.407][TRC][Px696c][Tx56b0] try_capture | BlueStacks  | enter 
[2021-11-09 09:17:03.408][TRC][Px696c][Tx56b0] try_capture | BlueStacks  | leave, 0 ms 
[2021-11-09 09:17:03.408][TRC][Px696c][Tx56b0] try_capture | BlueStacksInternational  | enter 
[2021-11-09 09:17:03.408][TRC][Px696c][Tx56b0] Handle: 0000000000010BC6 Name: BlueStacksInternational 
[2021-11-09 09:17:03.408][TRC][Px696c][Tx56b0] asst::Controller::call_command  | enter 
[2021-11-09 09:17:03.514][TRC][Px696c][Tx56b0] Call "C:\Program Files\BlueStacks_nxt\HD-Adb.exe" devices ret 0 , output size: 28 
[2021-11-09 09:17:03.514][TRC][Px696c][Tx56b0] output: List of devices attached



 
[2021-11-09 09:17:03.514][TRC][Px696c][Tx56b0] asst::Controller::call_command  | leave, 105 ms 
[2021-11-09 09:17:03.514][TRC][Px696c][Tx56b0] address  
[2021-11-09 09:17:03.514][TRC][Px696c][Tx56b0] try_capture | BlueStacksInternational  | leave, 106 ms 
[2021-11-09 09:17:03.515][TRC][Px696c][Tx56b0] try_capture | LDPlayer  | enter 
[2021-11-09 09:17:03.515][TRC][Px696c][Tx56b0] try_capture | LDPlayer  | leave, 0 ms 
[2021-11-09 09:17:03.515][TRC][Px696c][Tx56b0] try_capture | MuMuEmulator  | enter 
[2021-11-09 09:17:03.515][TRC][Px696c][Tx56b0] try_capture | MuMuEmulator  | leave, 0 ms 
[2021-11-09 09:17:03.515][TRC][Px696c][Tx56b0] try_capture | Nox  | enter 
[2021-11-09 09:17:03.515][TRC][Px696c][Tx56b0] try_capture | Nox  | leave, 0 ms 
[2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] try_capture | XYAZ  | enter 
[2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] try_capture | XYAZ  | leave, 0 ms 
[2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] try_capture | USB  | enter 
[2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] try_capture | USB  | leave, 0 ms 
[2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] try_capture | Remote  | enter 
[2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] try_capture | Remote  | leave, 0 ms 
[2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] asst::Assistance::catch_emulator  | leave, 109 ms 
[2021-11-09 09:17:03.517][TRC][Px696c][Tx56b0] asst::Assistance::catch_default  | leave, 110 ms 
```

**Comment by MistEO** [comment]
> @MistEO HyperV版还是不能自动连上 ![image](https://user-images.githubusercontent.com/24269465/140843751-18b5e137-a698-42fa-8d15-cf9b1fd16d14.png)
> 
> 似乎没有使用读取蓝叠配置文件的方法，而是使用蓝叠目录下的 adb，但是 `adb devices` 在 HyperV 下无法直接读出模拟器 ![image](https://user-images.githubusercontent.com/24269465/140844159-04e6183c-4bcb-4ab0-90fc-a8e78a54a10e.png)
> 
> **Log：**
> 
> ```
> [2021-11-09 09:17:03.406][TRC][Px696c][Tx56b0] asst::Assistance::catch_default  | enter 
> [2021-11-09 09:17:03.406][TRC][Px696c][Tx56b0] asst::Assistance::catch_emulator  | enter 
> [2021-11-09 09:17:03.407][TRC][Px696c][Tx56b0] asst::Assistance::stop  | enter 
> [2021-11-09 09:17:03.407][TRC][Px696c][Tx56b0] Stop | block 
> [2021-11-09 09:17:03.407][TRC][Px696c][Tx56b0] asst::Assistance::stop  | leave, 0 ms 
> [2021-11-09 09:17:03.407][TRC][Px696c][Tx56b0] try_capture | BlueStacks  | enter 
> [2021-11-09 09:17:03.408][TRC][Px696c][Tx56b0] try_capture | BlueStacks  | leave, 0 ms 
> [2021-11-09 09:17:03.408][TRC][Px696c][Tx56b0] try_capture | BlueStacksInternational  | enter 
> [2021-11-09 09:17:03.408][TRC][Px696c][Tx56b0] Handle: 0000000000010BC6 Name: BlueStacksInternational 
> [2021-11-09 09:17:03.408][TRC][Px696c][Tx56b0] asst::Controller::call_command  | enter 
> [2021-11-09 09:17:03.514][TRC][Px696c][Tx56b0] Call "C:\Program Files\BlueStacks_nxt\HD-Adb.exe" devices ret 0 , output size: 28 
> [2021-11-09 09:17:03.514][TRC][Px696c][Tx56b0] output: List of devices attached
> 
> 
> 
>  
> [2021-11-09 09:17:03.514][TRC][Px696c][Tx56b0] asst::Controller::call_command  | leave, 105 ms 
> [2021-11-09 09:17:03.514][TRC][Px696c][Tx56b0] address  
> [2021-11-09 09:17:03.514][TRC][Px696c][Tx56b0] try_capture | BlueStacksInternational  | leave, 106 ms 
> [2021-11-09 09:17:03.515][TRC][Px696c][Tx56b0] try_capture | LDPlayer  | enter 
> [2021-11-09 09:17:03.515][TRC][Px696c][Tx56b0] try_capture | LDPlayer  | leave, 0 ms 
> [2021-11-09 09:17:03.515][TRC][Px696c][Tx56b0] try_capture | MuMuEmulator  | enter 
> [2021-11-09 09:17:03.515][TRC][Px696c][Tx56b0] try_capture | MuMuEmulator  | leave, 0 ms 
> [2021-11-09 09:17:03.515][TRC][Px696c][Tx56b0] try_capture | Nox  | enter 
> [2021-11-09 09:17:03.515][TRC][Px696c][Tx56b0] try_capture | Nox  | leave, 0 ms 
> [2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] try_capture | XYAZ  | enter 
> [2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] try_capture | XYAZ  | leave, 0 ms 
> [2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] try_capture | USB  | enter 
> [2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] try_capture | USB  | leave, 0 ms 
> [2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] try_capture | Remote  | enter 
> [2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] try_capture | Remote  | leave, 0 ms 
> [2021-11-09 09:17:03.516][TRC][Px696c][Tx56b0] asst::Assistance::catch_emulator  | leave, 109 ms 
> [2021-11-09 09:17:03.517][TRC][Px696c][Tx56b0] asst::Assistance::catch_default  | leave, 110 ms 
> ```

emmm，看来我把问题想简单了_(:з」∠)_怎么adb devices都不输出的orz

**Comment by MistEO** [comment]
请尝试[v2.2版本](https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.2)  

![1P(~X (D9AAD9@B%SCAQZ_F](https://user-images.githubusercontent.com/18511905/144753815-9f9c2b54-6473-49ac-b826-e3b4b8791b0d.png)

**Comment by Meow-2** [comment]
> 请尝试[v2.2版本](https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.2)
> 
> ![1P(~X (D9AAD9@B%SCAQZ_F](https://user-images.githubusercontent.com/18511905/144753815-9f9c2b54-6473-49ac-b826-e3b4b8791b0d.png)

Nice！成功连接了，不过退出助手的时候似乎不会断开adb连接，希望下个版本能修复一下，美滋滋~

**Comment by MistEO** [comment]
> > 请尝试[v2.2版本](https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.2)
> > ![1P(~X (D9AAD9@B%SCAQZ_F](https://user-images.githubusercontent.com/18511905/144753815-9f9c2b54-6473-49ac-b826-e3b4b8791b0d.png)
> 
> Nice！成功连接了，不过退出助手的时候似乎不会断开adb连接，希望下个版本能修复一下，美滋滋~

不会断开连接是指没有`adb disconnect`吗？

**Comment by Meow-2** [comment]
> > > 请尝试[v2.2版本](https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.2)
> > > ![1P(~X (D9AAD9@B%SCAQZ_F](https://user-images.githubusercontent.com/18511905/144753815-9f9c2b54-6473-49ac-b826-e3b4b8791b0d.png)
> > 
> > 
> > Nice！成功连接了，不过退出助手的时候似乎不会断开adb连接，希望下个版本能修复一下，美滋滋~
>
> 不会断开连接是指没有`adb disconnect`吗？

退出助手之后，adb.exe 一直在后台运行，我猜测可能是没有`adb disconnect`
退出前：
![image](https://user-images.githubusercontent.com/67471300/144790293-bf2db63f-0e28-45bd-a1e9-c51c70e72961.png)
退出后：
![image](https://user-images.githubusercontent.com/67471300/144790514-3ed9fb62-7666-452e-b4dd-4f343eb9c54b.png)

**Comment by MistEO** [comment]
> > > > 请尝试[v2.2版本](https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.2)
> > > > ![1P(~X (D9AAD9@B%SCAQZ_F](https://user-images.githubusercontent.com/18511905/144753815-9f9c2b54-6473-49ac-b826-e3b4b8791b0d.png)
> > > 
> > > 
> > > Nice！成功连接了，不过退出助手的时候似乎不会断开adb连接，希望下个版本能修复一下，美滋滋~
> > 
> > 
> > 不会断开连接是指没有`adb disconnect`吗？
> 
> 退出助手之后，adb.exe 一直在后台运行，我猜测可能是没有`adb disconnect` 退出前： ![image](https://user-images.githubusercontent.com/67471300/144790293-bf2db63f-0e28-45bd-a1e9-c51c70e72961.png) 退出后： ![image](https://user-images.githubusercontent.com/67471300/144790514-3ed9fb62-7666-452e-b4dd-4f343eb9c54b.png)

确实有这个问题，应该是所有模拟器和ADB的都有，作为一个新问题吧
