### ISSUE TITLE
企鹅物流汇报能否自定义用户ID？

### ISSUE THREAD

**Issue by zhongfly** [MistEO/MeoAssistance-Arknights#28]
企鹅物流汇报可以通过“用户ID”登录/上传掉落，方便查看个人掉率

> 此用户 ID 非游戏内的 ID ，仅供本网站使用，用来标记您的上传身份。若无用户 ID，汇报一次掉落后即可拥有用户 ID。

登录的API应该是 https://penguin-stats.io/PenguinStats/swagger/swagger-ui.html#/operations/Account/loginUsingPOST
来源：https://penguin-stats.io/PenguinStats/swagger/swagger-ui.html#/

**Comment by MistEO** [comment]
与企鹅物流汇报的大佬们沟通，在请求标头中新增一个字段即可：
```
authorization: PenguinID your_id
```

辅助是直接使用`curl`进行请求的，所以直接修改`resource/config.json`中`options`.`penguinReportCmdLine`字段，新增这个字段即可，例如
```bash
"curl -H \"authorization: PenguinID 1234567\" -H \"Content-Type: application/json\" -d \"[body]\" \"https://penguin-stats.cn/PenguinStats/api/v2/report\" -v -i"
```

然后可以刷一次，通过`asst.log`中打印的`curl`的相关输出，确认是否成功了  

下次有空我把这个做个界面选项出来_(:з」∠)_

**Comment by MistEO** [comment]
已支持（在设置里）

https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.1.0-alpha
