### ISSUE TITLE
软件内更新关卡数据等内容

### ISSUE THREAD

**Issue by zhongfly** [MistEO/MeoAssistance-Arknights#32]
虽然我这想法似乎没啥必要，可能以后软件稳定后可以用上。
不必等待版本更新，仓库内更新相关数据后，软件就可以下载更新这些资源

**Comment by MistEO** [comment]
是的，有这个打算，现在每次更新我自己也嫌麻烦_(:з」∠)_

不过主要是关卡更新的频繁，我还打算把未知关卡的掉落识别也做出来

总之，下次一定！

**Comment by MistEO** [comment]
新版本已支持OTA更新公招、关卡资源文件

**Comment by zhongfly** [comment]
> 新版本已支持OTA更新公招、关卡资源文件

之前的程序更新后，都没有删除下载的压缩包，能不能在升级后做个清理

**Comment by MistEO** [comment]
> > 新版本已支持OTA更新公招、关卡资源文件
> 
> 之前的程序更新后，都没有删除下载的压缩包，能不能在升级后做个清理

好，get√
