### ISSUE TITLE
项目和代码文件的格式化

### ISSUE THREAD

**Issue by LiamSho** [MistEO/MeoAssistance-Arknights#34]
想着来学习学习顺便优化一下UI的，但说实话这个代码文件也太杂了。。。各种换行标识存在一个文件里。

建议添加 `.editorconfig` 文件来格式化代码文件。如果ok的话，我可以提交一个pr

P.S. VS2022和v143版本的C++工具链快正式版了，有准备升级吗？多装一个工具链是真的大（

**Comment by MistEO** [comment]
是说C#部分么，好耶好耶！坐等大佬的pr_(:з」∠)_

**Comment by MistEO** [comment]
https://github.com/MistEO/MeoAssistance-Arknights/pull/37
Close Issue，再次感谢大佬_(:з」∠)_
