### ISSUE TITLE
请问如何作用在 Visual Stdio 中的 Xamarin.Android 上

### ISSUE THREAD

**Issue by Meow-2** [MistEO/MeoAssistance-Arknights#35]
我的电脑开启了 Hyper-V，很多模拟器用不了，试过蓝叠5 Hyper-V 版，但 adb 端口每次启动都不一样，后来看到 VS 里的 android 模拟器兼容 Hyper-V，就想着用这个，请问该怎么更改配置？

**Comment by MistEO** [comment]
参照[连局域网手机的方法](
https://github.com/MistEO/MeoAssistance-Arknights#%E4%B8%8D%E4%BD%BF%E7%94%A8%E6%A8%A1%E6%8B%9F%E5%99%A8%E8%80%8C%E6%98%AF%E6%97%A0%E7%BA%BF%E8%BF%9E%E6%8E%A5%E5%AE%89%E5%8D%93%E6%89%8B%E6%9C%BA)，中的1、4、5条。

只要模拟器是16:9的，应该是全功能支持的，README里说的不支持主要是手机是宽屏的_(:з」∠)_

**Comment by Meow-2** [comment]
> 参照[连局域网手机的方法](https://github.com/MistEO/MeoAssistance-Arknights#%E4%B8%8D%E4%BD%BF%E7%94%A8%E6%A8%A1%E6%8B%9F%E5%99%A8%E8%80%8C%E6%98%AF%E6%97%A0%E7%BA%BF%E8%BF%9E%E6%8E%A5%E5%AE%89%E5%8D%93%E6%89%8B%E6%9C%BA)，中的1、4、5条。
> 
> 只要模拟器是16:9的，应该是全功能支持的，README里说的不支持主要是手机是宽屏的_(:з」∠)_

谢谢，连接上了，但最后还是折腾回蓝叠5 Hyper-V版了，VS 里那个模拟器是基于 qemu 的，最新版的 qemu-system-x86_64.exe 和 win11 间还有奇怪的 bug 没有修复，gpu 跑不上去，进方舟关卡的时间一长就卡死了

**Comment by MistEO** [comment]
https://github.com/MistEO/MeoAssistance-Arknights/issues/19#issuecomment-986255259
