### ISSUE TITLE
在流程尚未串联的现在，希望提供任务完成提醒

### ISSUE THREAD

**Issue by miyouzi** [MistEO/MeoAssistance-Arknights#38]
基建收菜、访问好友、刷理智 目前还没有串联起来而且耗时长，通常开启其中一个就去做别的事情了（比如看视频）。

完成后没有醒目提示，等想起来要去进行下一个通常隔了好一会了，希望能提供弹窗提醒，或者声音提示（考虑到加提示应该比串起来容易，就先加提示吧）

PS：基建放人可以加好感，基建换班策略希望能把人填满（观察目前宿舍可能会空出来），随便塞都可以

**Comment by MistEO** [comment]
还是串起来容易（bushi
https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.0.1
