### ISSUE TITLE
一直闪退

### ISSUE THREAD

**Issue by MistEO** [MistEO/MeoAssistance-Arknights#39]
目前群里有几个朋友反馈一启动就闪退，重启什么的也没效果。我自己找了三四台电脑都试了下都没出现这个问题，暂时没啥排查方向_(:з」∠)_程序启动后第一行执行的就是日志打印，但是出现闪退的也没打印日志。。

不过目前发现闪退的都有一个共性，就都是原厂的OEM系统，或者电脑店帮忙装的系统，所以可能还是环境问题，可以试试把[Visual C++ Redistributable](https://docs.microsoft.com/sl-SI/cpp/windows/latest-supported-vc-redist?view=msvc-160)、[.NET Framework 4.8](https://dotnet.microsoft.com/download/dotnet-framework/net48)都装一下看看有没有效果

如果有碰到闪退还懂一点相关知识的大佬能帮忙一起排查下就太感激不尽了QAQ

**Comment by wenp5454** [comment]
老电脑刚刚重新装机，也是一直全白然后闪退，安装完vc++环境后正常运行
