### ISSUE TITLE
活动图掉落汇报至企鹅数据时的bug

### ISSUE THREAD

**Issue by AlvISsReimu** [MistEO/MeoAssistance-Arknights#40]
如果是含有活动代币的掉落，汇报的request body一般是这样的：
```
{
  "server": "CN",
  "drops": [
    {
      "itemId": "30012",
      "dropType": "NORMAL_DROP",
      "quantity": 1
    },
    {
      "itemId": "",
      "dropType": "NORMAL_DROP",
      "quantity": 12
    }
  ],
  "source": "MeoAssistance",
  "version": "v1.3.3",
  "stageId": "act13side_04"
}
```
其中代币的`itemId`为空，按照目前企鹅后端的检查机制，会被认定为非法掉落。如果去掉这一项，或者把itemId填上代币的例如`act13side_token_model`就可以通过检查了；
另外有时也会见到`quantity`为0的，也会通不过检查：
```
    {
      "itemId": "",
      "dropType": "NORMAL_DROP",
      "quantity": 0
    }
```
如果可以改一下这两个小问题的话，就能有茫茫多的活动图掉落样本了
感谢你们工具提供的掉落数据~

**Comment by MistEO** [comment]
感谢站长大佬的反馈，问题已修复 https://github.com/MistEO/MeoAssistance-Arknights/commit/7f7eeb494dc09d93d4061ede42c60c44e84d645b，过几天会推送版本

**Comment by MistEO** [comment]
fixed
