### ISSUE TITLE
请问是如何实现100%识别干员成功率的呢？

### ISSUE THREAD

**Issue by ashesofdream** [MistEO/MeoAssistance-Arknights#45]
代码渣渣c++不太熟...自己写过个差不多的脚本，但选干员界面，图片模板匹配的相似率忽上忽下的。有时候轻轻拖动一下(改变一下干员的位置)，就会导致匹配失败...请问本项目找图的算法是什么呢以及有什么优化策略呢？

**Comment by MistEO** [comment]
两种思路

1. 识别干员技能
[本项目](https://github.com/MistEO/MeoAssistance-Arknights)和[AAH](https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper)用的是这种方法，需要先把干员技能ROI精确的裁剪出来（我时通过干员的心情笑脸然后移动固定坐标，AAH好像是通过干员框然后移动固定坐标），720p下是32*32，然后遍历当前设施所有可能的技能图标，挨个进行带mask的模板匹配，取得分最高的。一张图12个干员大概100-200ms

2. 识别干员名
隔壁[arkmover](https://github.com/Konano/arknights-mower)用的是这种策略，也是100%，基本思路是把干员名ROI裁剪出来，做个连通域拿到精确的干员名ROI，先拿OCR过一遍，如果OCR结果不对，再生成的所有干员名hash，挨个遍历，取得汉明举例最近的。耗时未知

**Comment by ashesofdream** [comment]
不小心点到关闭issue了....

**Comment by MistEO** [comment]
> > 
> 
> 直接对取到的图片(没有预处理？)进行模板匹配吗？模板匹配的相似度的最低阈值设置为多少呢？我写的时候是识别名字的，但是出现一个情况就是轻微拖动屏幕，相似度会大幅降低....

预处理就是把ROI精确的抠出来呀，不就是再说这个嘛

**Comment by MistEO** [comment]
感觉你没看明白我说的orz

**Comment by ashesofdream** [comment]
> > > 
> > 
> > 
> > 直接对取到的图片(没有预处理？)进行模板匹配吗？模板匹配的相似度的最低阈值设置为多少呢？我写的时候是识别名字的，但是出现一个情况就是轻微拖动屏幕，相似度会大幅降低....
> 
> 预处理就是把ROI精确的抠出来呀，不就是再说这个嘛

不是我是指匹配的时候，有采用其他方法处理吗... 灰度化之类的...

**Comment by MistEO** [comment]
> > > > 
> > > 
> > > 
> > > 直接对取到的图片(没有预处理？)进行模板匹配吗？模板匹配的相似度的最低阈值设置为多少呢？我写的时候是识别名字的，但是出现一个情况就是轻微拖动屏幕，相似度会大幅降低....
> > 
> > 
> > 预处理就是把ROI精确的抠出来呀，不就是再说这个嘛
> 
> 不是我是指匹配的时候，有采用其他方法处理吗... 灰度化之类的...

没有，带个掩码就好了

**Comment by ashesofdream** [comment]
谢了
