### ISSUE TITLE
下一步把基建换班搞出来！

### ISSUE THREAD

**Issue by MistEO** [MistEO/MeoAssistance-Arknights#5]
抄作业还是有难度了点

先搞个基建换班练练手~

**Comment by MistEO** [comment]
悲报，[chineseocr_lite](https://github.com/DayBreak-u/chineseocr_lite)对干员名字识别率堪忧。换了[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)试了下，效果稍微好一点，但是还是不能做到干员名全识别。。

**Comment by MistEO** [comment]
[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)的dll库太大了，1G+，谁愿意下载一个1G多的辅助软件呢。。。无了

**Comment by MistEO** [comment]
哎，又有了！初步的demo已经做好了！！！

**Comment by GengGode** [comment]
PaddleOCR好像可以自己训练出很小的库，几十MB，有人做过原神圣遗物词条的识别

**Comment by MistEO** [comment]
特征点检查，用了SURF，好！！！大佬们的建议太给力啦

![image](https://user-images.githubusercontent.com/18511905/129458491-35064745-c994-41ce-9c6f-2ee95780f0c1.png)

~~就是这个工程量orz，我慢慢截图去了~~

**Comment by fatinghenji** [comment]
加油！

**Comment by MistEO** [comment]
预计国庆前发一个尝鲜版本。不过现在对低分辨率的干员识别效果不是很好（有时候会识别漏干员，导致贸易站和制造站不是最优解组合）。其他的功能倒没啥，还是比较稳定的

**Comment by MistEO** [comment]
基建准备整体重构，由干员名识别，改为基建技能图标识别。正式版本估计还得等等了

**Comment by tkkcc** [comment]
要实现免设置的最高产出的基建换班，要考虑很多，制造站贸易站数量类型，所有干员心情和后勤技能需要一起考虑，而不是只考虑单个站选最高效干员组合就好。后勤技能只由干员名、房间名、精英化等级决定，这是可获取的。但是**求解最高产出换班的算法**我不知道有没有现成的。这是最难的。免设置的制造站换班，明日方舟速通 明日再肝 都有做，可以区别制造加速技能和等级上人，但远不是最高产出。

自定义设置的换班很需要的，每个策略可以是 时间点，房间，干员组合，每次定时启动时如果启动时间在该策略时间点前后5分钟内就执行该策略。默认3条策略，底下有一个新增策略按钮，顶上有一个总开关。这样就剩ocr稳定性了。

大佬轻喷 (o_ _)ﾉ

**Comment by DargonXuan** [comment]
有没有考虑抓数据包

**Comment by MistEO** [comment]
> 有没有考虑抓数据包

不考虑，这是我们做游戏辅助而不是外挂的底线_(:з」∠)_说起来现在识别已经搞定了2333

**Comment by DargonXuan** [comment]
> 要实现免设置的最高产出的基建换班，要考虑很多，制造站贸易站数量类型，所有干员心情和后勤技能需要一起考虑，而不是只考虑单个站选最高效干员组合就好。后勤技能只由干员名、房间名、精英化等级决定，这是可获取的。但是**求解最高产出换班的算法**我不知道有没有现成的。这是最难的。免设置的制造站换班，明日方舟速通 明日再肝 都有做，可以区别制造加速技能和等级上人，但远不是最高产出。
> 
> 自定义设置的换班很需要的，每个策略可以是 时间点，房间，干员组合，每次定时启动时如果启动时间在该策略时间点前后5分钟内就执行该策略。默认3条策略，底下有一个新增策略按钮，顶上有一个总开关。这样就剩ocr稳定性了。
> 
> 大佬轻喷 (o_ _)ﾉ

OCR稳定性可以换一种思路，就是抓数据包
“求解最高产出换班的算法”，已经有人做出来了，不过只有一个API

**Comment by DargonXuan** [comment]
实际上，

> > 有没有考虑抓数据包
> 
> 不考虑，这是我们做游戏辅助而不是外挂的底线_(:з」∠)_说起来现在识别已经搞定了2333

看你怎么理解辅助和外挂了，其实对方舟来说没有区别了。
可惜，我没空搞了。

https://github.com/DargonXuan/AutoArknights/blob/feature-mitmproxy/dev/%E8%A7%A3%E5%8C%85/%E5%9F%BA%E5%BB%BA.json5

**Comment by MistEO** [comment]
金丝雀版本已完成，close
