### ISSUE TITLE
在一键长草时，如果理智不足，会卡在选择理智药的界面没办法进行下一步操作

### ISSUE THREAD

**Issue by LBEILC** [MistEO/MeoAssistance-Arknights#50]
![image](https://user-images.githubusercontent.com/74463574/143970971-c22353a4-d71a-4eb6-a4cc-0d0350f0c8af.png)

**Comment by MistEO** [comment]
帮忙发下日志看看，辅助目录下的`asst.log`文件，可以直接拖进来

**Comment by LBEILC** [comment]
[asst .txt](https://github.com/MistEO/MeoAssistance-Arknights/files/7622305/asst.txt)

**Comment by MistEO** [comment]
知道问题了，感谢反馈，之后的版本修复_(:з」∠)_

**Comment by LBEILC** [comment]
> 知道问题了，感谢反馈，之后的版本修复_(:з」∠)_

大佬nb，大佬加油ヾ(◍°∇°◍)ﾉﾞ

**Comment by MistEO** [comment]
已修复

https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.1.0-alpha
