### ISSUE TITLE
未能领取日常奖励，可能是因为没有完成见习任务

### ISSUE THREAD

**Issue by LmeSzinc** [MistEO/MeoAssistance-Arknights#51]
单独执行 “领取任务奖励”，在游戏的任务奖励界面停留一段时间后，GUI显示任务完成，但实际未领取任何奖励。
在这个帐号上稳定复现，~~留下了没有好友的泪水~~。
附 log 和截图，[asst.log](https://github.com/MistEO/MeoAssistance-Arknights/files/7654038/asst.log)。

![gui](https://user-images.githubusercontent.com/37934724/144711974-779577df-9e54-446e-9b6c-bd26b3309327.png)

![emulator](https://user-images.githubusercontent.com/37934724/144711985-a3ce2df7-3568-496e-b604-8ce3db8257e4.png)

**Comment by MistEO** [comment]
感谢反馈，[v2.2版本](https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.2)已修复
