### ISSUE TITLE
当没有空的招募位置时，自动公招无法继续/结束

### ISSUE THREAD

**Issue by zhongfly** [MistEO/MeoAssistance-Arknights#52]
![image](https://user-images.githubusercontent.com/11155705/144818374-4ab47601-b48e-4822-928d-7b7ac5014653.png)

执行前，我自己已经手动完成了公招，然后开启“自动公招”任务
如图所示
期望的行为：视为任务已完成，跳过该任务
实际：没有任何操作，一直保持执行公招任务的状态

**Comment by zhongfly** [comment]
又试了一次，发现只是用时较久，1分钟后才发现完成

**Comment by MistEO** [comment]
没事你等一会他就结束了（其实是报错了），然后会继续执行下一个任务_(:з」∠)_

**Comment by MistEO** [comment]
> 没事你等一会他就结束了（其实是报错了），然后会继续执行下一个任务_(:з」∠)_

不过确实还是有优化空间的，没必要一直卡在这

**Comment by zhongfly** [comment]
> 没事你等一会他就结束了（其实是报错了），然后会继续执行下一个任务_(:з」∠)_

还有个小疑问，基建不能只加速无人机吗？（不勾选任何基建房间时）

**Comment by MistEO** [comment]
> > 没事你等一会他就结束了（其实是报错了），然后会继续执行下一个任务_(:з」∠)_
> 
> 还有个小疑问，基建不能只加速无人机吗？（不勾选任何基建房间时）

不能。想了想有点不好弄，现在的框架无人机其实是和制造站or贸易站绑定的。_(:з」∠)_~~下次一定~~

**Comment by MistEO** [comment]
> > 没事你等一会他就结束了（其实是报错了），然后会继续执行下一个任务_(:з」∠)_
> 
> 不过确实还是有优化空间的，没必要一直卡在这

v2.2.2已优化~
