### ISSUE TITLE
2.2.4版本仍不会自动使用理智药

### ISSUE THREAD

**Issue by zhang930427** [MistEO/MeoAssistance-Arknights#59]
win10  mumu模拟器。

**Comment by MistEO** [comment]
帮忙贴下日志吧，目录下的`asst.log`文件

**Comment by zhang930427** [comment]
[asst.log](https://github.com/MistEO/MeoAssistance-Arknights/files/7674238/asst.log)

**Comment by zhang930427** [comment]
> 帮忙贴下日志吧，目录下的`asst.log`文件

哇 大佬居然在线

**Comment by zhang930427** [comment]
> 定在线

哇 大佬居然在线

**Comment by zhang930427** [comment]
> 帮忙贴下日志吧，目录下的`asst.log`文件

且 不会自动解压 我每次都是手动解压 不知道是我电脑问题还是什么

**Comment by MistEO** [comment]
[tasks.zip](https://github.com/MistEO/MeoAssistance-Arknights/files/7674260/tasks.zip)

解压这个替换到`resource`下试试，这个问题好像只有mumu有，群里也有人说_(:з」∠)_先临时用一下

**Comment by zhang930427** [comment]
> [tasks.zip](https://github.com/MistEO/MeoAssistance-Arknights/files/7674260/tasks.zip)
> 
> 解压这个替换到`resource`下试试，这个问题好像只有mumu有，群里也有人说_(:з」∠)_先临时用一下

谢谢大佬 可以加下大佬的群嘛

**Comment by MistEO** [comment]
> > [tasks.zip](https://github.com/MistEO/MeoAssistance-Arknights/files/7674260/tasks.zip)
> > 解压这个替换到`resource`下试试，这个问题好像只有mumu有，群里也有人说_(:з」∠)_先临时用一下
> 
> 谢谢大佬 可以加下大佬的群嘛

可以鸭，672372860，（软件介绍翻到最后有群号的

**Comment by zhang930427** [comment]
> > > [tasks.zip](https://github.com/MistEO/MeoAssistance-Arknights/files/7674260/tasks.zip)
> > > 解压这个替换到`resource`下试试，这个问题好像只有mumu有，群里也有人说_(:з」∠)_先临时用一下
> > 
> > 
> > 谢谢大佬 可以加下大佬的群嘛
> 
> 可以鸭，672372860，（介绍的网页翻到最后有群号的

谢谢大佬 大佬辛苦啦

**Comment by MistEO** [comment]
fixed [v2.2.5](https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.2.5)
