### ISSUE TITLE
无论设置多少打关次数，只打一次就完成

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistance-Arknights#61]
![8J~ P` 3%DYTK$_@Y~6VSYG](https://user-images.githubusercontent.com/76220347/145419148-4623c862-24e7-4444-97eb-bfbff2469b48.png)

**Comment by MistEO** [comment]
帮忙发下日志吧~目录下`asst.log`文件

**Comment by guojunyu196** [comment]
[asst.log](https://github.com/MistEO/MeoAssistance-Arknights/files/7686029/asst.log)

**Comment by guojunyu196** [comment]
还有，无人机加速贸易站时，加速完成一个订单，加速下一个订单时会卡死

**Comment by guojunyu196** [comment]
![Screenshot_20211209-221201](https://user-images.githubusercontent.com/76220347/145420292-952a5099-9579-4cc3-9e70-a357e90033f9.png)
卡在这个界面不动

**Comment by MistEO** [comment]
是缓存不匹配，以前没遇到这种问题，这两天集中出现了好多，可能是yj这次更新改了啥。下个版本尝试我改下这块的逻辑

**Comment by guojunyu196** [comment]
好的，作者辛苦了！

**Comment by MistEO** [comment]
请体验 https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.3.0 版本

**Comment by MistEO** [comment]
> 请体验 https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.3.0 版本

版本问题较多，已撤包_(:з」∠)_

**Comment by MistEO** [comment]
已修复 https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.3.5
