### ISSUE TITLE
模拟器捕获失败问题

### ISSUE THREAD

**Issue by maidangdang1** [MistEO/MeoAssistance-Arknights#63]
最近蓝叠模拟器国际版的adb调试端口一直在变，每次打开蓝叠都要改一遍adb端口，有点奇怪

**Comment by MistEO** [comment]
请尝试[这个方法](https://github.com/MistEO/MeoAssistance-Arknights#%E8%93%9D%E5%8F%A0%E6%A8%A1%E6%8B%9F%E5%99%A8hyper-v%E7%89%88%E6%9C%AC)

**Comment by maidangdang1** [comment]
可以了😭 感谢
话说我以前用的时候都不用配置`bluestacks.conf`的呀，我的Windows功能也没开Hyper-V，怎么就用上了Hyper-V版？
我最近在配置wsl2，会是这个原因嘛？

**Comment by miyouzi** [comment]
> 可以了😭 感谢
> 话说我以前用的时候都不用配置`bluestacks.conf`的呀，我的Windows功能也没开Hyper-V，怎么就用上了Hyper-V版？
> 我最近在配置wsl2，会是这个原因嘛？

WSL2 基于 hyperV

**Comment by maidangdang1** [comment]
> > 可以了😭 感谢
> > 话说我以前用的时候都不用配置`bluestacks.conf`的呀，我的Windows功能也没开Hyper-V，怎么就用上了Hyper-V版？
> > 我最近在配置wsl2，会是这个原因嘛？
> 
> WSL2 基于 hyperV

哦哦 感谢感谢
