### ISSUE TITLE
自动更新到2.3.3版本后连不上模拟器

### ISSUE THREAD

**Issue by Ayusummer** [MistEO/MeoAssistance-Arknights#66]
今天早上打开应用提示自动更新后 linkStart 显示捕获模拟器窗口失败  
模拟器版本: 蓝叠 5.4.100.1026(Hyper-V)
log:
![image](https://user-images.githubusercontent.com/59549826/145652352-13715393-bf6c-414c-8db2-ffbde25d7f9e.png)

adb的调起路径有问题, 在 config.json 中 adb 的 path 加了个 `\\` 后可以正常调起 adb 并连上模拟器了
![image](https://user-images.githubusercontent.com/59549826/145652863-1172f791-15e9-4492-9e90-67d876e931bd.png)

![image](https://user-images.githubusercontent.com/59549826/145652575-38e51608-7679-4877-bc30-f322e5968993.png)

翻看了过往版本的 config.json path 这里本没有 `\\`, 因此认为可能是新版本的路径解析有些问题

**Comment by MistEO** [comment]
感谢反馈，确实是这个问题，已修复 [v2.3.4](https://github.com/MistEO/MeoAssistance-Arknights/releases/tag/v2.3.4)
