### ISSUE TITLE
更新后刷理智功能恢复正常了，基建卡在换人界面不不换人了

### ISSUE THREAD

**Issue by guojunyu196** [MistEO/MeoAssistance-Arknights#67]
![TTNWQ}I56EZ}MGFKM0%AS C](https://user-images.githubusercontent.com/76220347/145661252-01f1488a-b0ea-4b3a-a9a6-c5ceba2b79d3.png)
[asst.log](https://github.com/MistEO/MeoAssistance-Arknights/files/7696313/asst.log)

**Comment by guojunyu196** [comment]
和这个   基建控制中心出错，重复取消选择 #65   反馈的情况一样，重复取消选择，不换人

**Comment by MistEO** [comment]
你也是干员数量不足么？_(:з」∠)_

**Comment by guojunyu196** [comment]
充足，可使用的满理智的干员有21个

**Comment by MistEO** [comment]
感谢反馈，已修复，请尝试新版本~

https://github.com/MistEO/MeoAssistance-Arknights/releases
